/*
 * 
 * create_widgets.c
 *
 * INEEL BNCT Research Project
 * Montana State University - Bozeman
 *
 *
 * This is a set of procedures used to build various widgets necessary for the 
 * XContours program.  These procedures should be called so all widgets are 
 * built at the beginning of the initial procedure.  When one of the widgets is
 * desired to be used, it should be managed.
 *
 */


#include <Xm/MessageB.h>
#include "common.h"
#include "picshell.h"
#include "commonfcns.h"
#include "read_raw.h"
#include "preferences.h"
#include "contours_file.h"
#include "autoload.h"
#include "colorwash_file.h"
#include "global.h"

#include "launch_tools.h"
#include "libhelp.h"


/*
 * Generated by the ICS builderXcessory (BX).
 *
 *
 * Builder Xcessory 2.0.
 *
 */

extern caddr_t CONVERT( Widget, char *, char *, int, Boolean *);


/*
 * REQUIRED MOTIF INCLUDE FILES
 */
#include <Xm/Xm.h>
#include <Xm/CascadeB.h>
#include <Xm/DialogS.h>
#include <Xm/DrawingA.h>
#include <Xm/DrawnB.h>
#include <Xm/FileSB.h>
#include <Xm/Form.h>
#include <Xm/Frame.h>
#include <Xm/Label.h>
#include <Xm/List.h>
#include <Xm/MainW.h>
#include <Xm/MenuShell.h>
#include <Xm/PanedW.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/Scale.h>
#include <Xm/ScrolledW.h>
#include <Xm/SelectioB.h>
#include <Xm/Separator.h>
#include <Xm/Text.h>
#include <Xm/ToggleB.h>
#include <Xm/ToggleBG.h>


   
/*
 * create_contour_labels_options_shell()
 *
 * David Helzer 8/14/97
 */
 
Widget create_contour_labels_options_shell (Widget parent)
{
   Widget contour_labels_options_form;
   Widget large_image_label;
   Widget preview_image_label;
   Widget contour_labels_options_label;
   Widget apply_button;
   XmString message_to_display;
   
   DEBUG_TRACE_IN printf("Entering create_contour_labels_options_shell\n");

   XmRegisterConverters();
   
   contour_labels_options_shell = XtVaCreatePopupShell ("contour_labels_options_shell",
                                                        xmDialogShellWidgetClass, parent, 
                                                        NULL);
                                                        
   contour_labels_options_form = XtVaCreateWidget ("contour_labels_options_form",
                                                   xmFormWidgetClass, contour_labels_options_shell,
                                                   XmNheight, 280,
                                                   XmNwidth, 210,
                                                   NULL);
                                                   
                                                   
   message_to_display = XmStringCreateLtoR ("Contour Labels' Sizes\n", XmFONTLIST_DEFAULT_TAG);
                                                   
   contour_labels_options_label = XtVaCreateManagedWidget ("contour_labels_options_label",
                                                           xmLabelWidgetClass, contour_labels_options_form,
                                                           XmNlabelString, message_to_display,
                                                           XmNleftAttachment, XmATTACH_FORM,
                                                           XmNtopAttachment, XmATTACH_FORM,
                                                           XmNrightAttachment, XmATTACH_FORM,
                                                           NULL);
                                                           
                                                           
   message_to_display = XmStringCreateLtoR ("Attempt to Use Scalable Fonts", XmFONTLIST_DEFAULT_TAG);
   
   use_scalable_fonts_toggle = XtVaCreateManagedWidget ("use_scalable_fonts_toggle",
                                                        xmToggleButtonWidgetClass, contour_labels_options_form,
                                                        XmNlabelString, message_to_display,
                                                        XmNleftAttachment, XmATTACH_FORM,
                                                        XmNtopAttachment, XmATTACH_WIDGET,
                                                        XmNtopWidget, contour_labels_options_label,
                                                        NULL);


   message_to_display = XmStringCreateLtoR ("View Large Image Labels", XmFONTLIST_DEFAULT_TAG);

   view_large_image_labels_toggle = XtVaCreateManagedWidget ("view_large_image_labels_toggle",
                                                             xmToggleButtonWidgetClass, contour_labels_options_form,
                                                             XmNlabelString, message_to_display,
                                                             XmNleftAttachment, XmATTACH_FORM,
                                                             XmNtopAttachment, XmATTACH_WIDGET,
                                                             XmNtopWidget, use_scalable_fonts_toggle,
                                                             NULL);
                                                             
                  
   
   message_to_display = XmStringCreateLtoR ("Label Size", XmFONTLIST_DEFAULT_TAG);
   
   large_image_labels_scale = XtVaCreateManagedWidget ("large_image_labels_scale",
                                                       xmScaleWidgetClass, contour_labels_options_form,
                                                       XmNshowValue, TRUE,
                                                       XmNminimum, 1,
                                                       XmNmaximum, 300,
                                                       XmNorientation, XmHORIZONTAL,
                                                       XmNtitleString, message_to_display,
                                                       XmNleftAttachment, XmATTACH_FORM,
                                                       XmNtopAttachment, XmATTACH_WIDGET,
                                                       XmNtopWidget, view_large_image_labels_toggle,
                                                       XmNrightAttachment, XmATTACH_FORM,
                                                       NULL);
                                                       
   XtAddCallback (large_image_labels_scale, XmNvalueChangedCallback,
                  large_labels_scale_valchg_callback, NULL);

                                                       
   
    message_to_display = XmStringCreateLtoR ("Apply to Images", XmFONTLIST_DEFAULT_TAG);
    
    apply_button = XtVaCreateManagedWidget ("apply_button",
                                            xmPushButtonWidgetClass, contour_labels_options_form,
                                            XmNlabelString, message_to_display,
                                            XmNbottomAttachment, XmATTACH_FORM,
                                            XmNleftAttachment, XmATTACH_FORM,
                                            XmNrightAttachment, XmATTACH_FORM,
                                            NULL);
                                            
    XtAddCallback (apply_button, XmNactivateCallback,
                   update_label_size_callback, NULL);
                                                                          
                  
   message_to_display = XmStringCreateLtoR ("Label Size", XmFONTLIST_DEFAULT_TAG);                  
                                     
   preview_image_labels_scale = XtVaCreateManagedWidget ("preview_image_labels_scale", 
                                                         xmScaleWidgetClass, contour_labels_options_form,
                                                         XmNshowValue, TRUE,
                                                         XmNminimum, 1,
                                                         XmNmaximum, 150,
                                                         XmNorientation, XmHORIZONTAL,
                                                         XmNtitleString, message_to_display,
                                                         XmNleftAttachment, XmATTACH_FORM,
                                                         XmNrightAttachment, XmATTACH_FORM,
                                                         XmNbottomAttachment, XmATTACH_WIDGET,
                                                         XmNbottomWidget, apply_button,
                                                         NULL);
                                                         
   XtAddCallback (preview_image_labels_scale, XmNvalueChangedCallback,
                  preview_labels_scale_valchg_callback, NULL);
                                                         
   
   message_to_display = XmStringCreateLtoR ("View Preview Image Labels", XmFONTLIST_DEFAULT_TAG);
   
   view_preview_image_labels_toggle = XtVaCreateManagedWidget ("view_preview_image_labels_toggle",
                                                               xmToggleButtonWidgetClass, contour_labels_options_form,
                                                               XmNlabelString, message_to_display,
                                                               XmNleftAttachment, XmATTACH_FORM,
                                                               XmNbottomAttachment, XmATTACH_WIDGET,
                                                               XmNbottomWidget, preview_image_labels_scale,
                                                               NULL);

    XmStringFree (message_to_display);

   DEBUG_TRACE_OUT printf("Leaving create_contour_labels_options_shell\n");    

   return contour_labels_options_form;
}



/*
* CreatetextDialogShell - a procedure that creates a form widget that holds a label,
* a text-area widget, and two buttons (Exit and Save & Exit).  The label, text, and
* callbacks are defined globally to allow for easy property changes
* of them.  
*
* created by David Helzer 6-10-97
*/

Widget CreatetextDialogShell(Widget parent)
{
    Widget      textWidgetCancelPushButton;
    Widget      textWidgetApplyPushButton;
    Widget      textWidgetForm;

    DEBUG_TRACE_IN printf("Entering CreatetextDialogShell\n");

    XmRegisterConverters();


   #if defined (VERBOSE) || defined (MORE_VERBOSE)
      printf( "inside CreatetextDialogShell\n" );
   #endif /* VERBOSE */


   textDialogShell = XtVaCreatePopupShell("textDialogShell",
					  xmDialogShellWidgetClass, parent,
					  NULL);
   
   
   /* 
    * Create a form widget to hold a label, list area, and button
    */

   textWidgetForm = XtVaCreateWidget("textWidgetForm",
				     xmFormWidgetClass,
				     textDialogShell,
				     NULL);
       

   /* 
    * Create a label widget for the top of the form
    */

   textWidgetLabel = XtVaCreateManagedWidget ("textWidgetLabel",
				              xmLabelWidgetClass, textWidgetForm,
				              XmNtopAttachment, XmATTACH_FORM,
				              XmNleftAttachment, XmATTACH_FORM,
				              XmNrightAttachment, XmATTACH_FORM,
				              NULL);


   /* 
    * Create a text area widget in the center of the form.
    */

   textWidgetTextArea = XmCreateText (textWidgetForm, "textWidgetTextArea", NULL, 0);
   
   XtVaSetValues (textWidgetTextArea,
		  XmNeditMode, XmMULTI_LINE_EDIT,
		  XmNtopAttachment, XmATTACH_WIDGET,
		  XmNtopWidget, textWidgetLabel,
		  XmNleftAttachment, XmATTACH_FORM,
		  XmNrightAttachment, XmATTACH_FORM,
		  XmNbottomAttachment, XmATTACH_NONE,
		  XmNheight, 200,
		  NULL);
   
   XtManageChild (textWidgetTextArea);
   
   
   /* 
    * Create cancel button at the bottom of the form 
    */

   textWidgetCancelPushButton = XtVaCreateWidget("textWidgetCancelPushButton",
						 xmPushButtonWidgetClass,
						 textWidgetForm,
						 XmNlabelString, XmStringCreateLocalized("Cancel"),
						 XmNtopAttachment, XmATTACH_WIDGET,
						 XmNtopWidget, textWidgetTextArea,
						 XmNrightAttachment, XmATTACH_FORM,
						 NULL);

   XtManageChild (textWidgetCancelPushButton);
   

  /*
   * Create an Apply button at the bottom of the form
   */

   textWidgetApplyPushButton = XtVaCreateWidget("textWidgetApplyPushButton",
                                                 xmPushButtonWidgetClass,
                                                 textWidgetForm,
                                                 XmNlabelString,
                                                 XmStringCreateLocalized("Apply"),
                                                 XmNtopAttachment, XmATTACH_WIDGET,
                                                 XmNtopWidget, textWidgetTextArea,
                                                 XmNleftAttachment, XmATTACH_FORM,
                                                 NULL);

   XtManageChild (textWidgetApplyPushButton);
  
   /*
    * Add a callback for the Apply button. This callback is prototyped
    * in global.h and the code for it is in callbacks.c.
    */

   XtAddCallback (textWidgetApplyPushButton, XmNactivateCallback,
                  (XtCallbackProc)Apply_Contour_Levels_Callback, NULL);
                      
   DEBUG_TRACE_OUT printf("Leaving CreatetextDialogShell\n");

   return (textWidgetForm);
}




Widget CreatescaleDialogShell (Widget parent)
{
    Arg    	args[512];
    Boolean   	argok;
    Cardinal   	argcnt;
    Widget	scaleWidgetDismissPushButton;
    Widget	scaleWidgetSeparator;
    Widget 	retval;
    XmString	xmstr[32];

    DEBUG_TRACE_IN printf("Entering CreatescaleDialogShell\n");

    XmRegisterConverters();

   #if defined (VERBOSE) || defined (MORE_VERBOSE)
      printf( "inside CreatescaleDialogShell\n" );
   #endif /* VERBOSE */

    argcnt = 0;
    XtSetArg(args[argcnt], XmNwidth, 300); argcnt++;
    XtSetArg(args[argcnt], XmNheight, 133); argcnt++;
    scaleDialogShell = XtCreatePopupShell("scaleDialogShell",
		xmDialogShellWidgetClass,
		parent,
		args,
		argcnt);


    argcnt = 0;
    XtSetArg(args[argcnt], XmNresizePolicy, XmRESIZE_GROW); argcnt++;
    XtSetArg(args[argcnt], XmNheight, 133); argcnt++;
    scaleWidgetForm = XtCreateWidget("scaleWidgetForm",
		xmFormWidgetClass,
		scaleDialogShell,
		args,
		argcnt);

    retval = scaleWidgetForm;

    argcnt = 0;
    scaleWidgetDismissPushButton = XtCreateWidget("scaleWidgetDismissPushButton",
		xmPushButtonWidgetClass,
		scaleWidgetForm,
		args,
		argcnt);

    XtManageChild(scaleWidgetDismissPushButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNwidth, 300); argcnt++;
    scaleWidgetSeparator = XtCreateWidget("scaleWidgetSeparator",
		xmSeparatorWidgetClass,
		scaleWidgetForm,
		args,
		argcnt);

    XtManageChild(scaleWidgetSeparator);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNvalue, 10); argcnt++;
    XtSetArg(args[argcnt], XmNmaximum, 100); argcnt++;
    XtSetArg(args[argcnt], XmNminimum, 1); argcnt++;
    XtSetArg(args[argcnt], XmNorientation, XmHORIZONTAL); argcnt++;
    XtSetArg(args[argcnt], XmNshowValue, True); argcnt++;
    XtSetArg(args[argcnt], XmNwidth, 400); argcnt++;
    scaleWidget = XtCreateWidget("scaleWidget",
		xmScaleWidgetClass,
		scaleWidgetForm,
		args,
		argcnt);

    XtManageChild(scaleWidget);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNdefaultButton, scaleWidgetDismissPushButton); argcnt++;
    XtSetValues(scaleWidgetForm, args, argcnt);

    XtVaSetValues( scaleWidgetSeparator,
       XmNtopWidget, scaleWidget,
       NULL );

    XtVaSetValues( scaleWidgetDismissPushButton,
       XmNtopWidget, scaleWidgetSeparator,
       NULL );

    DEBUG_TRACE_OUT printf("Leaving CreatescaleDialogShell\n");

    return( retval );
}



Widget
CreatedoseDialogShell(Widget parent)
{
    Arg    	args[512];
    Boolean   	argok;
    Cardinal   	argcnt;
    Widget	doseDialogShell;
    Widget 	retval;
    XmString	xmstr[32];
#define NDOSE   9
    static char strlist[]="\
Boron Dose\n\
Gamma Dose\n\
Nitrogen Dose\n\
Fast Dose\n\
Group 1 Fluence\n\
Group 2 Fluence\n\
Thermal Fluence\n\
Other Dose\n\
Total Dose\
";

    DEBUG_TRACE_IN printf("Entering CreatedoseDialogShell\n");

    XmRegisterConverters();

    argcnt = 0;
    doseDialogShell = XtCreatePopupShell("doseDialogShell",
		xmDialogShellWidgetClass,
		parent,
		args,
		argcnt);


    argcnt = 0;
    XtSetArg(args[argcnt], XmNtextString, (xmstr[0]=XmStringCreateLtoR(
		"Total Dose", XmSTRING_DEFAULT_CHARSET))); argcnt++;
    XtSetArg(args[argcnt], XmNlistItems,
	CONVERT(parent, strlist,
	"XmStringTable", 0 /*133*/, &argok)); if(argok) argcnt++;
    XtSetArg(args[argcnt], XmNlistItemCount, NDOSE); argcnt++;
    XtSetArg(args[argcnt], XmNautoUnmanage, False ); argcnt++;
    XtSetArg(args[argcnt], XmNdialogTitle, XmStringCreateLtoR("Dose Options", XmSTRING_DEFAULT_CHARSET)); argcnt++;
    doseSelectionBox = XtCreateWidget("doseSelectionBox",
		xmSelectionBoxWidgetClass,
		doseDialogShell,
		args,
		argcnt);

    XmStringFree( xmstr[0] );

    XtUnmanageChild( XmSelectionBoxGetChild( doseSelectionBox, XmDIALOG_APPLY_BUTTON ) );
    XtUnmanageChild( XmSelectionBoxGetChild( doseSelectionBox, XmDIALOG_HELP_BUTTON ) );
    XtUnmanageChild( XmSelectionBoxGetChild( doseSelectionBox, XmDIALOG_SELECTION_LABEL ) );
    XtUnmanageChild( XmSelectionBoxGetChild( doseSelectionBox, XmDIALOG_TEXT ) );

    XtAddCallback(doseSelectionBox, XmNcancelCallback, UnmanageCallback, (caddr_t)0);
    XtAddCallback(doseSelectionBox, XmNokCallback, DoseOptionCallback, (caddr_t)0);
    retval = doseSelectionBox;

    DEBUG_TRACE_OUT printf("Leaving CreatedoseDialogShell\n");

    return( retval );
}



Widget
CreatefileSelectionDialogShell(Widget parent)
{
    Arg    	args[512];
    Boolean   	argok;
    Cardinal   	argcnt;
    Widget 	retval;
    XmString	xmstr[32];

    DEBUG_TRACE_IN printf("Entering CreateSelectionDialogShell\n");

    XmRegisterConverters();

    argcnt = 0;
    XtSetArg( args[argcnt], XmNallowShellResize, True ); argcnt++;
    fileSelectionDialogShell = XtCreatePopupShell("fileSelectionDialogShell",
		xmDialogShellWidgetClass,
		parent,
		args,
		argcnt);


    argcnt = 0;
    XtSetArg(args[argcnt], XmNmappedWhenManaged, True); argcnt++;
    XtSetArg(args[argcnt], XmNautoUnmanage, False); argcnt++; /* changed by mwf */
    XtSetArg(args[argcnt], XmNmustMatch, True); argcnt++;
    fileSelectionBox = XtCreateWidget("fileSelectionBox",
		xmFileSelectionBoxWidgetClass,
		fileSelectionDialogShell,
		args,
		argcnt);

    /* XXX FileSelectionCallbackXXX scares me. JJC */
    /*XtAddCallback(fileSelectionBox, XmNokCallback, FileSelectionCallbackXXX, (caddr_t) 0 ); */
    retval = fileSelectionBox;

    DEBUG_TRACE_OUT printf("Leaving CreateSelectionDialogShell\n");

    return( retval );
}



/*
 * CreateeditContourColorsDialogShell() -- Creates a widget that contains
 * a label, list, radiobox, and two button widgets.  The list will hold the
 * contour levels to be drawn.  After selecting one of these, a color can be
 * selected from the color buttons in the radiobox.  Any changes can be used for 
 * the current session only by selecting the "Apply" button.  The changes can be 
 * saved for later sessions (in the external file contour_levels.txt) by 
 * selecting the "Save and Apply" button.  The label, list, color buttons, and
 * "Apply" callbacks are defined globally for a more generic procedure that
 * could be used in other places.  
 *
 * David Helzer     July 7, 1997
 */
 
Widget CreateeditContourColorsDialogShell (Widget parent)
{
   Widget    retval;
   Widget    contourColorsSelection;
   Widget    contourColorsForm;
   Widget    contourColorsDialogShell;
   Widget    contourColorsListForm, contourColorsTopForm;
   Widget    contourColorsApplyPushButton;
   short     count;
   char *    colors[] = {"white", "black", "red", "green", 
                         "blue", "cyan", "magenta", "yellow"};
    
   DEBUG_TRACE_IN printf( "Entering CreateeditContourColorsDialogShell\n" );
  
   XmRegisterConverters();
   
  
   contourColorsDialogShell = XtVaCreatePopupShell ("contourColorsDialogShell",
                                                    xmDialogShellWidgetClass,
                                                    parent, 
                                                    NULL);
   
   
   /* 
    * Create a form widget to hold a label, list widget, radiobox, and two buttons
    */
    
   contourColorsForm = XtVaCreateWidget ("contourColorsForm",
                                         xmFormWidgetClass,
                                         contourColorsDialogShell,
                                         NULL);
                                          
   retval = contourColorsForm;
   

  
   /* 
    * Create a label widget to be displayed at the top of the form. 
    */
    
    contourColorsLabel = XtVaCreateManagedWidget ("contourColorsLabel", 
                                                  xmLabelWidgetClass, contourColorsForm,
                                                  XmNtopAttachment, XmATTACH_FORM,
                                                  XmNleftAttachment, XmATTACH_FORM,
                                                  XmNrightAttachment, XmATTACH_FORM,
                                                  NULL);
                                         
                                         
   /*
    * Create a form widget to hold the list and radio box widgets
    */
    
    contourColorsTopForm = XtVaCreateManagedWidget ("contourColorsTopForm",
                                                    xmFormWidgetClass, contourColorsForm,
                                                    XmNtopAttachment, XmATTACH_WIDGET,
                                                    XmNtopWidget, contourColorsLabel,
                                                    XmNleftAttachment, XmATTACH_FORM,
                                                    XmNrightAttachment, XmATTACH_FORM,
                                                    NULL);

   /* 
    * Create a radio box to the right of the list widget 
    * displaying the colors available.
    */
    
    contourColorsSelection = XmCreateRadioBox (contourColorsTopForm,
                                               "contourColorsSelection", NULL, 0);
                                               
    XtManageChild (contourColorsSelection);
    
    XtVaSetValues (contourColorsSelection,
                   XmNtopAttachment, XmATTACH_FORM,
                   /*XmNtopWidget, contourColorsLabel,*/
                   XmNrightAttachment, XmATTACH_FORM,
                   NULL);
    
    for (count = 0; count < NUMBER_CONTOUR_COLORS; count ++) {
        contourColorsSelectionButtons[count] = XtVaCreateManagedWidget (colors[count], 
                                                                     xmToggleButtonWidgetClass,
                                                                     contourColorsSelection,
                                                                     NULL);
        /* 
         * Add Callback for this button -- prototyped in global.h; code in
         * callbacks.c
         */
        XtAddCallback (contourColorsSelectionButtons[count], XmNvalueChangedCallback,
                       Select_Contour_Color_Callback, NULL);
    }
                                          
                         
    /*
     * Create a list widget (within a form widget) to display the contour 
     * levels to be drawn.
     */
     
    contourColorsListForm = XtVaCreateManagedWidget ("contourColorsListForm", 
                                                     xmFormWidgetClass, contourColorsTopForm,
                                                     XmNtopAttachment, XmATTACH_FORM,
                                                     /*XmNtopWidget, contourColorsLabel,*/
                                                     XmNleftAttachment, XmATTACH_FORM,
                                                     XmNrightAttachment, XmATTACH_WIDGET,
                                                     XmNrightWidget, contourColorsSelection,
                                                     NULL);

    contourColorsList = XmCreateScrolledList (contourColorsListForm, 
                                              "contourColorsList", NULL, 0);
                                              

    XtManageChild (contourColorsList);
    
    XtVaSetValues (contourColorsList,
                   XmNselectionPolicy, XmSINGLE_SELECT,
                   XmNvisibleItemCount, 17,
                   XmNtopAttachment, XmATTACH_FORM,
                   XmNleftAttachment, XmATTACH_FORM,
                   XmNrightAttachment, XmATTACH_FORM,
                   XmNbottomAttachment, XmATTACH_FORM,
                   NULL);
                                   
  
   /* 
    * Add a callback for the list widget.  This callback is prototyped in 
    * global.h and defined in callbacks.c
    */
    
   XtAddCallback (contourColorsList, XmNsingleSelectionCallback,
                  Select_Contour_Level_Callback, NULL);
                                                       
                                     
   /*
    * Create an "Apply" button at the bottom of the form
    */
    
   contourColorsApplyPushButton = XtVaCreateManagedWidget
                                  ("contourColorsApplyPushButton",
                                   xmPushButtonWidgetClass,
                                   contourColorsForm,
                                   XmNlabelString, XmStringCreateLocalized ("Apply"),
                                   XmNtopAttachment, XmATTACH_WIDGET,
                                   XmNtopWidget, contourColorsTopForm,
                                   XmNleftWidget, XmATTACH_FORM,
                                   NULL);   
                                   
                                   
   /*
    * Add a callback for the Apply button.  This callback is prototyped in 
    * global.h and the code for it is in callbacks.c
    */
    
    XtAddCallback (contourColorsApplyPushButton, XmNactivateCallback,
                   (XtCallbackProc)Apply_Contour_Colors_Callback, NULL);    
                                          
   DEBUG_TRACE_OUT printf( "Leaving CreateeditContourColorsDialogShell\n" );    

   return retval;
}




Widget
CreatemainWindow(Widget parent)
{
    Arg    	args[512];
    Boolean   	argok;
    Cardinal   	argcnt;
    XmString    xstring;
    Widget	analysisCascadeButton;
    Widget	analysisPulldownMenu;
    Widget	changeFOVpushButton;
    Widget	separator2;
    Widget	colorCascadeButton;
    Widget	colorPulldownMenu;
    Widget	colorPulldownShell;
    Widget	complimentPushButton;
    Widget	contour_levels_push_button;
    Widget	contourSmoothPushButton;
    Widget	doseComponentPushButton;
    Widget      doseFactorPushButton;
    Widget	editColorPushButton;
    Widget	editParametersPushButton;
    Widget	equalizePushButton;
    Widget	exitPushButton;
    Widget	fileCascadeButton;
    Widget	filePulldownMenu;
    Widget	filePulldownShell;
    Widget	formatsPulldownShell;
    Widget	helpCascadeButton;
    Widget	helpDismissPulldownShell;
    Widget	helpPulldownMenu;
    Widget	helpPulldownShell;
    Widget	helpPushButton;

    Widget      qshLoadPushButton;      /* Added by MTC 6/10/98 */
    Widget      qshSeparator;
    Widget      checkVersionButton;     /* Added by MTC 7/15/98 */
    Widget      launchSeparator;        /* Added by MTC 7/20/98 */

    /**************************
     * The following have been replaced with LT_make_launch_menu()
     * mbr 1-7-99
     *********************************
     * Widget      launchSubmenu;    
     * Widget      launchCascade;   
     * Widget      launchButton;       
     * Widget      sera3dButton;              
     * Widget      imageToolsButton;
     *********************************/

    Widget	loadImagePushButton;
    Widget      autoLoaderPushButton;
    Widget	smartLoaderPushButton;
    Widget	unloadImagePushButton;
    Widget	logo;
    Widget	logoMenuForm;
    Widget 	logoMenuFrame;
    Widget	mainWindow;
    Widget      parentPane;        /* parent of the next two - added by MWF */
    Widget      textAreaForm;      /* bottom text area for input - added by MWF */
    Widget      text;              /* text widget - Text area for screen dumps - MWF */
    Widget	mainWindowForm;    /* form for the main window - same as before but now
				    * it's not the main parent as parentPane is now at a
				    * higher level than the mainWindowForm - MWF */
    Widget	mainWindowMenuBar;
    Widget	optionPulldownMenu;
    Widget	optionPulldownShell;
    Widget	optionsCascadeButton;
    Widget      printImageCascadeButton, printImagePullrightMenu;
    Widget	printImagePushButton, printAllPushButton;
    Widget	smoothPushButton;
    Widget 	retval;
    Widget      formatsCascadeButton;
    Widget      formatsPulldownMenu;
    Widget      gifFormatToggleButton;
    Widget      jpegFormatToggleButton;
    Widget      loadColorPushButton;
    Widget      reloadDefaultColormap;
    Widget      qshFormatToggleButton;
    Widget      rawImageFormatToggleButton;
    Widget      reserveColorPushButton;
    Widget	xcontoursFrame;
    Widget	xcontoursLabel;
    Widget      colormapPushButton;
    Widget      picPushButton;
    Widget      generate_contours_file_button;
    Widget      preferences_pushbutton;
    Widget      contour_labels_options_pushbutton;

    XmString	xmstr[32];

    XmRegisterConverters();

    DEBUG_TRACE_IN printf( "Entering CreatemainWindow\n" );
	
    retval = mainWindow = XtVaCreateManagedWidget("mainWindow",
		xmFrameWidgetClass, parent,
		XmNshadowType, XmSHADOW_IN,
    		XmNshadowThickness, 5,
    		NULL);

    XtAddCallback(mainWindow, XmNdestroyCallback, ExitCallback, (XtPointer) 0);

    /* Instead of just a mainWindowForm, the parentPane will contain the
     * mainWindowForm and below it will be a textAreaForm for use in labelling
     * before printing the image set.  MWF 03-20-96
     */
    argcnt = 0;
    parentPane = XtCreateManagedWidget("parentPane",
		xmPanedWindowWidgetClass, mainWindow,
		args, argcnt);

    argcnt = 0;
    /* Do resize the area for images when you resize the window. */
    XtSetArg( args[argcnt], XmNskipAdjust, False ); argcnt++;
    mainWindowForm = XtCreateManagedWidget("mainWindowForm",
		xmFormWidgetClass, parentPane,
		args, argcnt);

    argcnt = 0;
    /* Don't resize the text area when you resize the window. */
    XtSetArg( args[argcnt], XmNskipAdjust, True ); argcnt++;
    textAreaForm = XtCreateManagedWidget("textAreaForm",
					   xmFormWidgetClass, parentPane,
					   args, argcnt);
    
    argcnt = 0;
    XtSetArg( args[argcnt], XmNeditMode, XmMULTI_LINE_EDIT ); argcnt++;
    XtSetArg( args[argcnt], XmNwordWrap, True ); argcnt++;
    XtSetArg( args[argcnt], XmNheight, 1 ); argcnt++;
    text = XmCreateText(textAreaForm, "text", args, argcnt);
    XtManageChild(text);
    
    SetFormPercent(text, 0, 0, 100, 100);

    logoMenuFrame = XtVaCreateManagedWidget("logoMenuFrame",
		xmFrameWidgetClass, mainWindowForm,
		XmNshadowType, XmSHADOW_OUT,
		XmNshadowThickness, 2,
		XmNtopAttachment, XmATTACH_FORM,
		XmNleftAttachment, XmATTACH_FORM,
		XmNrightAttachment, XmATTACH_FORM,
		NULL);

    logoMenuForm = XtVaCreateManagedWidget("logoMenuForm",
		xmFormWidgetClass, logoMenuFrame,
		NULL);

    logo = InstallLogo(logoMenuForm);
    XtVaSetValues(logo,
		XmNtopAttachment, XmATTACH_FORM,
		XmNleftAttachment, XmATTACH_FORM,
		XmNbottomAttachment, XmATTACH_FORM,
		NULL);

    xcontoursFrame = XtVaCreateManagedWidget("xcontoursFrame",
		xmFrameWidgetClass, logoMenuForm,
		XmNshadowType, XmSHADOW_IN,
		XmNshadowThickness, 2,
		XmNtopAttachment, XmATTACH_FORM,
		XmNleftAttachment, XmATTACH_WIDGET,
		XmNleftWidget, logo,
		XmNrightAttachment, XmATTACH_FORM,
		NULL);

    xcontoursLabel = XtVaCreateManagedWidget("BNCT:  seraDose",
		xmLabelWidgetClass, xcontoursFrame,
		XmNalignment, XmALIGNMENT_CENTER,
                XmNheight, 50,					     
		NULL);

    mainWindowMenuBar = XtVaCreateManagedWidget("mainWindowMenuBar",
		xmRowColumnWidgetClass, logoMenuForm,
		XmNrowColumnType, XmMENU_BAR,
		XmNtopAttachment, XmATTACH_WIDGET,
		XmNtopWidget, xcontoursFrame,
		XmNbottomAttachment, XmATTACH_FORM,
		XmNleftAttachment, XmATTACH_WIDGET,
		XmNleftWidget, logo,
		XmNrightAttachment, XmATTACH_FORM,
		NULL);

    image_matrix.window = make_pic_window(mainWindowForm);
    XtVaSetValues(image_matrix.window,
		  XmNtopAttachment, XmATTACH_WIDGET,
		  XmNtopWidget, logoMenuFrame,
		  XmNleftAttachment, XmATTACH_FORM,
		  XmNrightAttachment, XmATTACH_FORM,
		  XmNbottomAttachment, XmATTACH_FORM,
		  XmNheight, image_matrix.rc_height,
		  XmNwidth, image_matrix.rc_width,
		  NULL);

/**** MENU BAR STUFF *****/


    argcnt = 0;
    XtSetArg(args[argcnt], XmNwidth, 1); argcnt++;
    XtSetArg(args[argcnt], XmNheight, 1); argcnt++;
    filePulldownShell = XtCreatePopupShell("filePulldownShell",
		xmMenuShellWidgetClass,
		mainWindowMenuBar,
		args,
		argcnt);


    argcnt = 0;
    XtSetArg(args[argcnt], XmNborderWidth, 0); argcnt++;
    XtSetArg(args[argcnt], XmNrowColumnType, XmMENU_PULLDOWN); argcnt++;
    filePulldownMenu = XtCreateWidget("filePulldownMenu",
		xmRowColumnWidgetClass,
		filePulldownShell,
		args,
		argcnt);

    /*********** Load QSH button added by MTC 6/10/98 ****************/
    qshLoadPushButton 
               = XtVaCreateManagedWidget ( "Load QSH Pair",
                                           xmPushButtonWidgetClass,
					   filePulldownMenu,
					   /*XmNaccelerator, "Ctrl<Key>Q",
                                           XmNacceleratorText,
                                               XmStringCreateSimple("Ctrl+Q"),*/
                                           XmNsensitive, TRUE,
					   NULL );

    XtAddCallback ( qshLoadPushButton, XmNactivateCallback,
                    qshLoadCallback, NULL );

    qshDoseLoadRightMenu 
        = XmCreatePulldownMenu ( filePulldownMenu, "dose_pull_right", NULL, 0 );

    qshDoseLoadCascadeButton
        = XtVaCreateManagedWidget ( "Load Dose(s) on QSH", xmCascadeButtonWidgetClass,
				    filePulldownMenu,
				    XmNsubMenuId, qshDoseLoadRightMenu,
				    XmNsensitive, FALSE,
				    NULL );

    qshDoseLoadAllPushButton
        = XtVaCreateManagedWidget ( "Load All Doses", xmPushButtonWidgetClass,
				    qshDoseLoadRightMenu,
				    NULL );

    XtAddCallback ( qshDoseLoadAllPushButton, XmNactivateCallback,
                    qshDoseLoadCallback, (XtPointer) 1 );

    qshDoseLoadSinglePushButton
        = XtVaCreateManagedWidget ( "Load Dose on Current Image", xmPushButtonWidgetClass,
				    qshDoseLoadRightMenu,
				    NULL );

    XtAddCallback ( qshDoseLoadSinglePushButton, XmNactivateCallback,
                    qshDoseLoadCallback, (XtPointer) 0 );

    /******** Load 3D contour file *********/
    qshDoseLoad3DPushButton
        = XtVaCreateManagedWidget ( "Load 3D Contour File", xmPushButtonWidgetClass,
				    qshDoseLoadRightMenu,
				    NULL );

    XtAddCallback ( qshDoseLoad3DPushButton, XmNactivateCallback,
                    load_concatenated_contour_file_CB, (XtPointer) 0 );
    /********* MTC 5/13/99 *****************/
    
    qshMaskLoadRightMenu 
        = XmCreatePulldownMenu ( filePulldownMenu, "mask_pull_right", NULL, 0 );

    qshMaskLoadCascadeButton
        = XtVaCreateManagedWidget ( "Load Mask(s) on QSH", xmCascadeButtonWidgetClass,
				    filePulldownMenu,
				    XmNsubMenuId, qshMaskLoadRightMenu,
				    XmNsensitive, FALSE,
				    NULL );

    qshMaskLoadAllPushButton
        = XtVaCreateManagedWidget ( "Load All Masks", xmPushButtonWidgetClass,
				    qshMaskLoadRightMenu,
				    NULL );

    XtAddCallback ( qshMaskLoadAllPushButton, XmNactivateCallback,
                    qshMaskLoadCallback, (XtPointer) 1 );

    qshMaskLoadSinglePushButton
        = XtVaCreateManagedWidget ( "Load Mask on Current Image", xmPushButtonWidgetClass,
				    qshMaskLoadRightMenu,
				    NULL );

    XtAddCallback ( qshMaskLoadSinglePushButton, XmNactivateCallback,
                    qshMaskLoadCallback, (XtPointer) 0 );

    /******** Load 3D contour file *********/
    qshMaskLoad3DPushButton
        = XtVaCreateManagedWidget ( "Load 3D Mask File", xmPushButtonWidgetClass,
				    qshMaskLoadRightMenu,
				    NULL );

    XtAddCallback ( qshMaskLoad3DPushButton, XmNactivateCallback,
                    load_concatenated_mask_file_CB, (XtPointer) 0 );
    /********* MTC 5/14/99 *****************/
    
    qshRemoveImagesWODoseButton 
               = XtVaCreateManagedWidget ( "Remove Images without Doses",
                                           xmPushButtonWidgetClass,
					   filePulldownMenu,
					   /*XmNaccelerator, "Ctrl<Key>R",
                                           XmNacceleratorText,
                                              XmStringCreateSimple("Ctrl+R"),*/
                                           XmNsensitive, FALSE,
					   NULL );

    XtAddCallback ( qshRemoveImagesWODoseButton, XmNactivateCallback,
                    remove_images_without_dose_CB, NULL ); 

    qshSeparator = XtVaCreateManagedWidget("qshSeparator",
		                           xmSeparatorWidgetClass,
		                           filePulldownMenu,
	                   	           NULL);

    /****************************************************************/

    argcnt = 0;
    XtSetArg(args[argcnt], XmNuserData, 0); argcnt++;
    autoLoaderPushButton = XtCreateWidget ("autoLoaderPushButton",
                xmPushButtonWidgetClass,
                filePulldownMenu,
                args,
                argcnt);

    XtAddCallback(autoLoaderPushButton, XmNactivateCallback, 
                  auto_loader_callback, NULL);
    XtManageChild(autoLoaderPushButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNuserData, 0); argcnt++;
    smartLoaderPushButton = XtCreateWidget("smartLoaderPushButton",
		xmPushButtonWidgetClass,
		filePulldownMenu,
		args,
		argcnt);

    XtAddCallback(smartLoaderPushButton, XmNactivateCallback, rawImageFileLoaderCB, (caddr_t) 1 );
    XtManageChild(smartLoaderPushButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNuserData, 0); argcnt++;
    loadImagePushButton = XtCreateWidget("loadImagePushButton",
		xmPushButtonWidgetClass,
		filePulldownMenu,
		args,
		argcnt);

    XtAddCallback(loadImagePushButton, XmNactivateCallback, rawImageFileLoaderCB, (caddr_t) 0 );
    XtManageChild(loadImagePushButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNuserData, 1); argcnt++;
    XtSetArg(args[argcnt], XmNsensitive, False); argcnt++;
    loadDosePushButton = XtCreateWidget("loadDosePushButton",
		xmPushButtonWidgetClass,
		filePulldownMenu,
		args,
		argcnt);

    XtAddCallback(loadDosePushButton, XmNactivateCallback, FilePopupCallback, (caddr_t) 1);
    XtManageChild(loadDosePushButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNuserData, 2); argcnt++;
    XtSetArg(args[argcnt], XmNsensitive, False); argcnt++;
    loadMaskPushButton = XtCreateWidget("loadMaskPushButton",
		xmPushButtonWidgetClass,
		filePulldownMenu,
		args,
		argcnt);

    XtAddCallback(loadMaskPushButton, XmNactivateCallback, FilePopupCallback, (caddr_t) 2);
    XtManageChild(loadMaskPushButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNuserData, 0); argcnt++;
    unloadImagePushButton = XtCreateWidget("unloadImagePushButton",
		xmPushButtonWidgetClass,
		filePulldownMenu,
		args,
		argcnt);

    XtAddCallback(unloadImagePushButton, XmNactivateCallback, rawImageFileLoaderDoneCB, (caddr_t) 2 );
    XtManageChild(unloadImagePushButton);


   /*
    * ---------- Start of print buttons ----------
    */

    /*
     * Set up a print cascade button with the print options.
     */
  
    printImagePullrightMenu = XmCreatePulldownMenu
    (
       filePulldownMenu, "pullright",
       NULL, 0
    );

    xstring = XmStringCreate ("Print", char_set);
    printImageCascadeButton = XtVaCreateManagedWidget
    (
       "printImagePushButton", xmCascadeButtonWidgetClass,
       filePulldownMenu,
       XmNsubMenuId, printImagePullrightMenu,
       XmNlabelString, xstring,
       NULL
    );
    XmStringFree (xstring);

    xstring = XmStringCreate ("Print Selected", char_set);
    printImagePushButton = XtVaCreateManagedWidget
    (
       "printImagePushButton", xmPushButtonWidgetClass,
       printImagePullrightMenu,
       XmNlabelString, xstring,
       NULL
    );
    XmStringFree (xstring);

    XtAddCallback
    (
        printImagePushButton, 
        XmNactivateCallback, 
        (XtCallbackProc)PrintImageCallback, (XtPointer) 0
    );

/*
    xstring = XmStringCreate ("Print All", char_set);
    printAllPushButton = XtVaCreateManagedWidget
    (
       "printAllPushButton", xmPushButtonWidgetClass,
       printImagePullrightMenu,
       XmNlabelString, xstring,
       NULL
    );
    XmStringFree (xstring);

    XtAddCallback
    (
        printAllPushButton, 
        XmNactivateCallback, 
        PrintImageCallback, (XtPointer) 1
    );
*/

    xstring = XmStringCreate ("Print Window", char_set);
    printAllPushButton = XtVaCreateManagedWidget
    (
       "printAllPushButton", xmPushButtonWidgetClass,
       printImagePullrightMenu,
       XmNlabelString, xstring,
       NULL
    );
    XmStringFree (xstring);

    XtAddCallback
    (
        printAllPushButton, 
        XmNactivateCallback, 
        (XtCallbackProc)PrintImageCallback, (XtPointer) 3
    );

   /*
    * ---------- End of print buttons ----------
    */
 
    /*  MTC Commented these out 5/18/99 *****************

        These generate contour and colorwash buttons
        were intended to be used for creating files to
        be used by sera3d.  However, sera3d now reads
        in the concatenated contour files and colorwashes
        the image set and does not need these.  They don't
        work either... another reason I commented them out!
    ********************************************************/
    /*    
    XtSetArg(args[argcnt], XmNsensitive, True); argcnt++;
    XtSetArg(args[argcnt], XmNvisibleWhenOff, True); argcnt++;
    generate_contours_file_button = XtCreateWidget("generate_contours_file_button",
                                                   xmPushButtonWidgetClass,
                                                   filePulldownMenu,
                                                   args,
                                                   argcnt);
                                                   
    XtAddCallback (generate_contours_file_button, XmNactivateCallback, 
                   generate_contours_file_callback, NULL);
    XtManageChild (generate_contours_file_button);
    

    XtSetArg(args[argcnt], XmNsensitive, True); argcnt++;
    XtSetArg(args[argcnt], XmNvisibleWhenOff, True); argcnt++;
    generate_colorwash_file_button = XtCreateWidget("generate_colorwash_file_button",
                                                    xmPushButtonWidgetClass,
                                                    filePulldownMenu,
                                                    args,
                                                    argcnt);

    XtVaSetValues (generate_colorwash_file_button, 
                   XmNsensitive, FALSE,
                   NULL);

    XtAddCallback (generate_colorwash_file_button, XmNactivateCallback,
                   generate_colorwash_file_callback, NULL);
    XtManageChild (generate_colorwash_file_button);
    */

    
    /*** Launch menu added by MTC 7/20/98 ***/

    launchSeparator
               = XtVaCreateManagedWidget ( "launchSeparator",
                                           xmSeparatorWidgetClass,
					   filePulldownMenu,
					   NULL );

    /*** New launch menu added by MBR 1-7-99 ***/

    LT_make_launch_menu( filePulldownMenu, "seraDose" );
    
/*
    launchSubmenu = XmCreatePulldownMenu(filePulldownMenu, "ls",NULL,0);
    launchCascade = XtVaCreateManagedWidget("Launch",
					     xmCascadeButtonWidgetClass,
					     filePulldownMenu,
					     XmNsubMenuId, launchSubmenu,
					     NULL);
    imageToolsButton = XtVaCreateManagedWidget("Image Tools",
					       xmPushButtonWidgetClass,
					       launchSubmenu, NULL, 0);
    sera3dButton = XtVaCreateManagedWidget("Sera3D",
					   xmPushButtonWidgetClass,
					   launchSubmenu, NULL, 0);
					   
    XtAddCallback (imageToolsButton, XmNactivateCallback, 
                   launchAppCallback, NULL);
    XtAddCallback (sera3dButton, XmNactivateCallback, 
                   launchAppCallback, NULL);
*/

 
    /** Version button added by MTC 7/16/98 **/

    checkVersionButton
               = XtVaCreateManagedWidget ( "Check Version",
                                           xmPushButtonWidgetClass,
					   filePulldownMenu,
					   NULL );

    XtAddCallback ( checkVersionButton, XmNactivateCallback,
                    checkVersionCallback, NULL ); 

    /*******************************************/

    argcnt = 0;
    exitPushButton = XtCreateWidget("exitPushButton",
		xmPushButtonWidgetClass,
		filePulldownMenu,
		args,
		argcnt);

    XtAddCallback(exitPushButton, XmNactivateCallback, ExitCallback, (caddr_t)0);
    XtManageChild(exitPushButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNsubMenuId, filePulldownMenu); argcnt++;
    fileCascadeButton = XtCreateWidget("fileCascadeButton",
		xmCascadeButtonWidgetClass,
		mainWindowMenuBar,
		args,
		argcnt);

    XtManageChild(fileCascadeButton);


    argcnt = 0;
    XtSetArg(args[argcnt], XmNwidth, 1); argcnt++;
    XtSetArg(args[argcnt], XmNheight, 1); argcnt++;
    helpPulldownShell = XtCreatePopupShell("helpPulldownShell",
		xmMenuShellWidgetClass,
		mainWindowMenuBar,
		args,
		argcnt);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNborderWidth, 0); argcnt++;
    XtSetArg(args[argcnt], XmNrowColumnType, XmMENU_PULLDOWN); argcnt++;
    helpPulldownMenu = XtCreateWidget("helpPulldownMenu",
		xmRowColumnWidgetClass,
		helpPulldownShell,
		args,
		argcnt);

    argcnt = 0;
    helpPushButton = XtCreateWidget("Help on Context",
		xmPushButtonWidgetClass,
		helpPulldownMenu,
		args,
		argcnt);

    set_preference_directory( "/SeraDose/" );
    XtAddCallback(helpPushButton, XmNactivateCallback, ContextHelpCallback, (XtPointer) parent ); /*helpTopLevelShell );*/

    XtManageChild(helpPushButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNsensitive, True); argcnt++;
    XtSetArg(args[argcnt], XmNsubMenuId, helpPulldownMenu); argcnt++;
    helpCascadeButton = XtCreateWidget("helpCascadeButton",
		xmCascadeButtonWidgetClass,
		mainWindowMenuBar,
		args,
		argcnt);

    XtManageChild(helpCascadeButton);



    argcnt = 0;
    XtSetArg(args[argcnt], XmNwidth, 1); argcnt++;
    XtSetArg(args[argcnt], XmNheight, 1); argcnt++;
    colorPulldownShell = XtCreatePopupShell("colorPulldownShell",
		xmMenuShellWidgetClass,
		mainWindowMenuBar,
		args,
		argcnt);


    argcnt = 0;
    XtSetArg(args[argcnt], XmNborderWidth, 0); argcnt++;
    XtSetArg(args[argcnt], XmNrowColumnType, XmMENU_PULLDOWN); argcnt++;
    colorPulldownMenu = XtCreateWidget("colorPulldownMenu",
		xmRowColumnWidgetClass,
		colorPulldownShell,
		args,
		argcnt);

    argcnt = 0;
    editColorPushButton = XtCreateWidget("editColorPushButton",
		xmPushButtonWidgetClass,
		colorPulldownMenu,
		args,
		argcnt);

    XtAddCallback(editColorPushButton, XmNactivateCallback, 
		  (XtCallbackProc)ContourColorsPopupCallback, (caddr_t)0);
    XtManageChild(editColorPushButton);

    argcnt = 0;
    reserveColorPushButton = XtCreateWidget("reserveColorPushButton",
		xmPushButtonWidgetClass,
		colorPulldownMenu,
		args,
		argcnt);

    XtAddCallback(reserveColorPushButton, XmNactivateCallback, ScalePopupCallback, (caddr_t) 1);
    XtManageChild(reserveColorPushButton);

    argcnt = 0;
    loadColorPushButton = XtCreateWidget("loadColorPushButton",
		xmPushButtonWidgetClass,
		colorPulldownMenu,
		args,
		argcnt);

    XtAddCallback(loadColorPushButton, XmNactivateCallback, CT_loadCB, NULL);
    XtManageChild(loadColorPushButton);

    reloadDefaultColormap
        = XtVaCreateManagedWidget ( "Reload Default Color Table", xmPushButtonWidgetClass,
                                    colorPulldownMenu, NULL );

    XtAddCallback ( reloadDefaultColormap, XmNactivateCallback, CT_reloadColormapCB, NULL );
    
    argcnt = 0;
    colormapPushButton = XtCreateWidget("colormapPushButton",
		xmPushButtonWidgetClass,
		colorPulldownMenu,
		args,
		argcnt);

    XtAddCallback(colormapPushButton, XmNactivateCallback, color_toolCB, (XtPointer)1);
    XtManageChild(colormapPushButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNsubMenuId, colorPulldownMenu); argcnt++;
    colorCascadeButton = XtCreateWidget("colorCascadeButton",
		xmCascadeButtonWidgetClass,
		mainWindowMenuBar,
		args,
		argcnt);

    XtManageChild(colorCascadeButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNwidth, 1); argcnt++;
    XtSetArg(args[argcnt], XmNheight, 1); argcnt++;
    optionPulldownShell = XtCreatePopupShell("optionPulldownShell",
		xmMenuShellWidgetClass,
		mainWindowMenuBar,
		args,
		argcnt);


    argcnt = 0;
    XtSetArg(args[argcnt], XmNborderWidth, 0); argcnt++;
    XtSetArg(args[argcnt], XmNrowColumnType, XmMENU_PULLDOWN); argcnt++;
    optionPulldownMenu = XtCreateWidget("optionPulldownMenu",
		xmRowColumnWidgetClass,
		optionPulldownShell,
		args,
		argcnt);
		
		
    argcnt = 0;
    XtSetArg(args[argcnt], XmNuserData, 0); argcnt++;
    preferences_pushbutton = XtCreateWidget("preferences_pushbutton",
                                            xmPushButtonWidgetClass,
                                            optionPulldownMenu,
                                            args,
                                            argcnt);
                                  
    XtAddCallback(preferences_pushbutton, XmNactivateCallback, 
                  preferences_callback, NULL);          
    XtManageChild(preferences_pushbutton);


    argcnt = 0;
    doseComponentPushButton = XtCreateWidget("doseComponentPushButton",
		xmPushButtonWidgetClass,
		optionPulldownMenu,
		args,
		argcnt);

    XtAddCallback(doseComponentPushButton, XmNactivateCallback, DosePopupCallback, NULL);
    XtManageChild(doseComponentPushButton);

    argcnt = 0;
    doseFactorPushButton = XtCreateWidget("doseFactorPushButton",
		xmPushButtonWidgetClass,
		optionPulldownMenu,
		args,
		argcnt);

    XtAddCallback(doseFactorPushButton, XmNactivateCallback, DoseFactorCallback, &current_driver_data);
    XtManageChild(doseFactorPushButton);

    argcnt = 0;
    contour_levels_push_button = XtCreateWidget("contour_levels_push_button",
		xmPushButtonWidgetClass,
		optionPulldownMenu,
		args,
		argcnt);
    XtAddCallback(contour_levels_push_button, XmNactivateCallback, 
		  (XtCallbackProc)contour_levels_callback, NULL);
    XtManageChild(contour_levels_push_button);

    /* Commented out by MTC *******/
    /* Option not implemented yet */
    /*argcnt = 0;
      XtSetArg(args[argcnt], XmNsensitive, False); argcnt++;
      editParametersPushButton = XtCreateWidget("editParametersPushButton",
      xmPushButtonWidgetClass,
      optionPulldownMenu,
      args,
      argcnt);

      XtAddCallback(editParametersPushButton, XmNactivateCallback, EditParametersCallback, (caddr_t)0);
      XtManageChild(editParametersPushButton);*/
    /*******************************/
    
    XtSetArg(args[argcnt], XmNsensitive, True); argcnt++;
    XtSetArg(args[argcnt], XmNvisibleWhenOff, True); argcnt++;
    contour_labels_options_pushbutton = XtCreateWidget("contour_labels_options_pushbutton",
                                                       xmPushButtonWidgetClass,
                                                       optionPulldownMenu,
                                                       args,
                                                       argcnt);
                                                
    XtAddCallback(contour_labels_options_pushbutton, XmNactivateCallback,
                  contour_labels_options_callback, NULL);
    XtManageChild(contour_labels_options_pushbutton);
                                               
    /* Commented out by MTC 5/18/99 ***********************************/
    /* Contour Smoothing was to be used to smooth our blocky looking
       contours.  However, since we are now using contours made up
       of a 40X40 grid, linear interpolation is already pretty smooth.
       I'm not sure if this feature was implemented, but prior to my
       commenting it out, the option was insensitive in the options
       menu*/
    /******************************************************************/

    /*argcnt = 0;
      XtSetArg(args[argcnt], XmNsensitive, False); argcnt++;
      contourSmoothPushButton = XtCreateWidget("contourSmoothPushButton",
      xmPushButtonWidgetClass,
      optionPulldownMenu,
      args,
      argcnt);
      
      XtAddCallback(contourSmoothPushButton, XmNactivateCallback, ScalePopupCallback, (caddr_t) 3);
      XtManageChild(contourSmoothPushButton);*/
    /*******************************/
    
    argcnt = 0;
    changeFOVpushButton = XtCreateWidget("changeFOVpushButton",
		xmPushButtonWidgetClass,
		optionPulldownMenu,
		args,
		argcnt);

    XtAddCallback(changeFOVpushButton, XmNactivateCallback, 
		  (XtCallbackProc)FOVchangeCallback, (caddr_t) 4);
    XtManageChild(changeFOVpushButton);

    argcnt = 0;
    separator2 = XtCreateWidget("separator2",
		xmSeparatorWidgetClass,
		optionPulldownMenu,
		args,
		argcnt);

    XtManageChild(separator2);

    XtSetArg(args[argcnt], XmNsensitive, True); argcnt++;
    XtSetArg(args[argcnt], XmNvisibleWhenOff, True); argcnt++;
    applyToAllButton = XtCreateWidget("applyToAllButton",
		xmToggleButtonWidgetClass,
		optionPulldownMenu,
		args,
		argcnt);

    XtManageChild(applyToAllButton);

    XtAddCallback ( applyToAllButton, XmNvalueChangedCallback,
		    apply_mask_to_all_CB, (XtPointer) 1 );

    XtSetArg(args[argcnt], XmNsensitive, True); argcnt++;
    XtSetArg(args[argcnt], XmNvisibleWhenOff, True); argcnt++;
    masksReplaceImagesButton = XtCreateWidget("masksReplaceImagesButton",
		xmToggleButtonWidgetClass,
		optionPulldownMenu,
		args,
		argcnt);

    XtAddCallback(masksReplaceImagesButton, XmNvalueChangedCallback, 
		  (XtCallbackProc)masksReplaceImagesCallback, (caddr_t) 0);
    XtManageChild(masksReplaceImagesButton);
    
    XtSetArg(args[argcnt], XmNsensitive, True); argcnt++;
    XtSetArg(args[argcnt], XmNvisibleWhenOff, True); argcnt++;
    view_contour_lines_button = XtCreateWidget("view_contour_lines_button",
                                               xmToggleButtonWidgetClass,
                                               optionPulldownMenu,
                                               args,
                                               argcnt);

    XtAddCallback(view_contour_lines_button, XmNvalueChangedCallback, 
                  view_contour_lines_callback, NULL);                                               
    XtManageChild(view_contour_lines_button);
    
    XtSetArg(args[argcnt], XmNsensitive, True); argcnt++;
    XtSetArg(args[argcnt], XmNvisibleWhenOff, True); argcnt++;
    view_contour_colorwash_button = XtCreateWidget("view_contour_colorwash_button",
                                                   xmToggleButtonWidgetClass,
                                                   optionPulldownMenu,
                                                   args,
                                                   argcnt);

    XtAddCallback(view_contour_colorwash_button, XmNvalueChangedCallback,
                  view_contour_colorwash_callback, NULL);                                                   
    XtManageChild(view_contour_colorwash_button);    

    argcnt = 0;
    XtSetArg(args[argcnt], XmNsubMenuId, optionPulldownMenu); argcnt++;
    optionsCascadeButton = XtCreateWidget("optionsCascadeButton",
		xmCascadeButtonWidgetClass,
		mainWindowMenuBar,
		args,
		argcnt);

    XtManageChild(optionsCascadeButton);
    /*
    argcnt = 0;
    XtSetArg(args[argcnt], XmNwidth, 1); argcnt++;
    XtSetArg(args[argcnt], XmNheight, 1); argcnt++;
    formatsPulldownShell = XtCreatePopupShell("formatsPulldownShell",
					      xmMenuShellWidgetClass,
					      mainWindowMenuBar,
					      args,
					      argcnt);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNradioBehavior, True); argcnt++;
    XtSetArg(args[argcnt], XmNrowColumnType, XmMENU_PULLDOWN); argcnt++;
    formatsPulldownMenu = XtCreateWidget("formatsPulldownMenu",
		xmRowColumnWidgetClass,
		formatsPulldownShell,
		args,
		argcnt);



    XtSetArg(args[argcnt], XmNsensitive, False); argcnt++;
    XtSetArg(args[argcnt], XmNvisibleWhenOff, True); argcnt++;
    gifFormatToggleButton = XtCreateWidget("gifFormatToggleButton",
		xmToggleButtonWidgetClass,
		formatsPulldownMenu,
		args,
		argcnt);

    XtAddCallback(gifFormatToggleButton, XmNvalueChangedCallback, ImageFormat, (caddr_t)"gif");
    XtManageChild(gifFormatToggleButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNsensitive, False); argcnt++;
    XtSetArg(args[argcnt], XmNvisibleWhenOff, True); argcnt++;
    jpegFormatToggleButton = XtCreateWidget("jpegFormatToggleButton",
		xmToggleButtonWidgetClass,
		formatsPulldownMenu,
		args,
		argcnt);

    XtAddCallback(jpegFormatToggleButton, XmNvalueChangedCallback, ImageFormat, (caddr_t)"jpeg");
    XtManageChild(jpegFormatToggleButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNsensitive, False); argcnt++;
    XtSetArg(args[argcnt], XmNvisibleWhenOff, True); argcnt++;
    qshFormatToggleButton = XtCreateWidget("qshFormatToggleButton",
		xmToggleButtonWidgetClass,
		formatsPulldownMenu,
		args,
		argcnt);

    XtAddCallback(qshFormatToggleButton, XmNvalueChangedCallback, ImageFormat, (caddr_t)"qsh");
    XtManageChild(qshFormatToggleButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNvisibleWhenOff, True); argcnt++;
    XtSetArg(args[argcnt], XmNset, True); argcnt++;
    rawImageFormatToggleButton = XtCreateWidget("rawImageFormatToggleButton",
		xmToggleButtonWidgetClass,
		formatsPulldownMenu,
		args,
		argcnt);

    XtAddCallback(rawImageFormatToggleButton, XmNvalueChangedCallback, ImageFormat, (caddr_t)"raw");
    XtManageChild(rawImageFormatToggleButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNsubMenuId, formatsPulldownMenu); argcnt++;
    formatsCascadeButton = XtCreateWidget("formatsCascadeButton",
		xmCascadeButtonWidgetClass,
		mainWindowMenuBar,
		args,
		argcnt);

    XtManageChild(formatsCascadeButton);
    */

    argcnt = 0;
    XtSetArg(args[argcnt], XmNwidth, 1); argcnt++;
    XtSetArg(args[argcnt], XmNheight, 1); argcnt++;
    helpDismissPulldownShell = XtCreatePopupShell("helpDismissPulldownShell",
		xmMenuShellWidgetClass,
		mainWindowMenuBar,
		args,
		argcnt);

    /*
    argcnt = 0;
    XtSetArg(args[argcnt], XmNborderWidth, 0); argcnt++;
    XtSetArg(args[argcnt], XmNrowColumnType, XmMENU_PULLDOWN); argcnt++;
    analysisPulldownMenu = XtCreateWidget("analysisPulldownMenu",
		xmRowColumnWidgetClass,
		helpDismissPulldownShell,
		args,
		argcnt);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNsensitive, False); argcnt++;
    complimentPushButton = XtCreateWidget("complimentPushButton",
		xmPushButtonWidgetClass,
		analysisPulldownMenu,
		args,
		argcnt);

    XtAddCallback(complimentPushButton, XmNactivateCallback, AnalysisCallback, (caddr_t) 0);
    XtManageChild(complimentPushButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNsensitive, False); argcnt++;
    equalizePushButton = XtCreateWidget("equalizePushButton",
		xmPushButtonWidgetClass,
		analysisPulldownMenu,
		args,
		argcnt);

    XtAddCallback(equalizePushButton, XmNactivateCallback, AnalysisCallback, (caddr_t) 1);
    XtManageChild(equalizePushButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNsensitive, False); argcnt++;
    smoothPushButton = XtCreateWidget("smoothPushButton",
		xmPushButtonWidgetClass,
		analysisPulldownMenu,
		args,
		argcnt);

    XtAddCallback(smoothPushButton, XmNactivateCallback, AnalysisCallback, (caddr_t) 2);
    XtManageChild(smoothPushButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNsubMenuId, analysisPulldownMenu); argcnt++;
    analysisCascadeButton = XtCreateWidget("analysisCascadeButton",
		xmCascadeButtonWidgetClass,
		mainWindowMenuBar,
		args,
		argcnt);

    XtManageChild(analysisCascadeButton);
    */
    argcnt = 0;
    XtSetArg(args[argcnt], XmNmenuHelpWidget, helpCascadeButton); argcnt++;
    XtSetValues(mainWindowMenuBar, args, argcnt);

    DEBUG_TRACE_OUT printf( "Leaving CreatemainWindow\n" );

    return( retval );
}



Widget CreatehelpMainWindow (Widget parent)
{
    Arg    	args[512];
    Cardinal   	argcnt;
    /*SUPPRESS 591*/
    Boolean   	argok;
    Widget 	retval;
    /*SUPPRESS 591*/
    Widget	mainWindow;
    Widget	helpMainWindowMenuBar;
    Widget	helpDismissPulldownShell;
    Widget	helpDismissPulldownMenu;
    Widget	helpDismissPushButton;
    Widget	helpDismissCascadeButton;
    Widget	helpMainWindowScrolledWindow;
    Widget	helpMainWindowText;

    DEBUG_TRACE_IN printf( "Entering CreatehelpMainWindow\n" );

    XmRegisterConverters();

    argcnt = 0;
    XtSetArg(args[argcnt], XmNwidth, 668); argcnt++;
    XtSetArg(args[argcnt], XmNheight, 680); argcnt++;
    mainWindow = XtCreateWidget("mainWindow",
		xmMainWindowWidgetClass,
		parent,
		args,
		argcnt);

    retval = mainWindow;

    argcnt = 0;
    XtSetArg(args[argcnt], XmNrowColumnType, XmMENU_BAR); argcnt++;
    helpMainWindowMenuBar = XtCreateWidget("helpMainWindowMenuBar",
		xmRowColumnWidgetClass,
		mainWindow,
		args,
		argcnt);

    XtManageChild(helpMainWindowMenuBar);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNwidth, 1); argcnt++;
    XtSetArg(args[argcnt], XmNheight, 1); argcnt++;
    helpDismissPulldownShell = XtCreatePopupShell("helpDismissPulldownShell",
		xmMenuShellWidgetClass,
		helpMainWindowMenuBar,
		args,
		argcnt);


    argcnt = 0;
    XtSetArg(args[argcnt], XmNborderWidth, 0); argcnt++;
    XtSetArg(args[argcnt], XmNrowColumnType, XmMENU_PULLDOWN); argcnt++;
    helpDismissPulldownMenu = XtCreateWidget("helpDismissPulldownMenu",
		xmRowColumnWidgetClass,
		helpDismissPulldownShell,
		args,
		argcnt);


    argcnt = 0;
    helpDismissPushButton = XtCreateWidget("helpDismissPushButton",
		xmPushButtonWidgetClass,
		helpDismissPulldownMenu,
		args,
		argcnt);

    XtAddCallback(helpDismissPushButton, XmNactivateCallback, PopdownCallback, (caddr_t) parent );

    XtManageChild(helpDismissPushButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNsubMenuId, helpDismissPulldownMenu); argcnt++;
    helpDismissCascadeButton = XtCreateWidget("helpDismissCascadeButton",
		xmCascadeButtonWidgetClass,
		helpMainWindowMenuBar,
		args,
		argcnt);

    XtManageChild(helpDismissCascadeButton);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNscrollingPolicy, XmAUTOMATIC); argcnt++;
    XtSetArg(args[argcnt], XmNscrollBarDisplayPolicy, XmAS_NEEDED); argcnt++;
    helpMainWindowScrolledWindow = XtCreateWidget("helpMainWindowScrolledWindow",
		xmScrolledWindowWidgetClass,
		mainWindow,
		args,
		argcnt);

    XtManageChild(helpMainWindowScrolledWindow);

    argcnt = 0;
    XtSetArg(args[argcnt], XmNvalue, "         1         2         3         4         5         6         7\n\
1234567890123456789012345678901234567890123456789012345678901234567890\n\
3\n\
4\n\
5\n\
6\n\
7\n\
8\n\
9\n\
10\n\
11\n\
12\n\
13\n\
14\n\
15\n\
16\n\
17\n\
18\n\
19\n\
20\n\
21\n\
22\n\
23\n\
24\n\
25\n\
26\n\
27\n\
28\n\
29\n\
30\n\
31\n\
32\n\
33\n\
34\n\
35\n\
36\n\
37\n\
38\n\
39\n\
40"); argcnt++;
    XtSetArg(args[argcnt], XmNeditMode, XmMULTI_LINE_EDIT); argcnt++;
    XtSetArg(args[argcnt], XmNeditable, False); argcnt++;
    XtSetArg(args[argcnt], XmNcolumns, 70); argcnt++;
    XtSetArg(args[argcnt], XmNrows, 40); argcnt++;
    XtSetArg(args[argcnt], XmNcursorPositionVisible, False); argcnt++;
    helpMainWindowText = XtCreateWidget("helpMainWindowText",
		xmTextWidgetClass,
		helpMainWindowScrolledWindow,
		args,
		argcnt);

    XtManageChild(helpMainWindowText);

    DEBUG_TRACE_OUT printf( "Leaving CreatehelpMainWindow\n" );

    return( retval );
}



Widget CreatemaskWindow(Widget w)
{
    Widget maskScreen, shell, form, reset, set;
    Widget disMiss;
    int n = 0, i;
    Arg args[10];

    DEBUG_TRACE_IN printf( "Entering CreatemaskWindow\n" );

    shell = XtCreatePopupShell("Select regions for masking", topLevelShellWidgetClass, w, NULL,0);

    /* allocate a mask toggle buffer */
    if ((mask_pack.buffer = (unsigned char *)MT_malloc(WINDOW_WIDTH*WINDOW_HEIGHT)) == NULL)
    {
	printf("Unable to allocate data buffer in process_region()\n");
    }
 
    dummy_buffer = mask_pack.buffer;
    for (i=0; i<WINDOW_WIDTH*WINDOW_HEIGHT; i++)
    {
        dummy_buffer[i] = 255;   /* default the masks to 1 */
    }

    if ((mask_pack.masks = (unsigned char *)MT_malloc(256)) == NULL)
    {
	printf("Unable to allocate mask buffer in process_region()\n");
    }

    dummy_masks = mask_pack.masks;

    for (i=0; i<256; i++)
    {
        dummy_masks[i] = FALSE; /* No masks is default */
    }

    form = XtCreateManagedWidget("form", xmFormWidgetClass, shell, NULL, 0);
    
    maskScreen 
        = XtVaCreateManagedWidget ( "mask_screen", xmDrawingAreaWidgetClass,
				    form,
				    XmNwidth,           256,
				    XmNheight,          256,
				    XmNtopAttachment,   XmATTACH_FORM,
				    XmNleftAttachment,  XmATTACH_FORM,
				    XmNrightAttachment, XmATTACH_FORM,
				    NULL );

    XtAddEventHandler ( maskScreen, ExposureMask, FALSE, 
			(XtEventHandler)mask_imageEH, NULL );
    XtAddCallback ( maskScreen, XmNinputCallback, 
		    (XtCallbackProc)region_selectCB, NULL );
    
    /* Added this button to make it easier to select one or all masks 
       MTC 12/14/98 */
    applyToAllButton2
        = XtVaCreateManagedWidget ( "Apply To All   ", 
				    xmToggleButtonWidgetClass,
				    form,
				    XmNtopAttachment,   XmATTACH_WIDGET,
				    XmNtopWidget,       maskScreen,
				    XmNleftAttachment,  XmATTACH_FORM,
				    XmNrightAttachment, XmATTACH_FORM,
				    XmNset,             TRUE,
				    NULL );

    XtAddCallback ( applyToAllButton2, XmNvalueChangedCallback, 
		    apply_mask_to_all_CB, (XtPointer) 0 );

    reset 
        = XtVaCreateManagedWidget ( "Clear All Masks",
				    xmPushButtonWidgetClass,
				    form,
				    XmNtopAttachment,   XmATTACH_WIDGET,
				    XmNtopWidget,       applyToAllButton2,
				    XmNleftAttachment,  XmATTACH_FORM,
				    XmNrightAttachment, XmATTACH_FORM,
				    NULL );

    XtAddCallback ( reset, XmNactivateCallback, 
		    (XtCallbackProc)clear_masksCB, NULL );

    set = XtVaCreateManagedWidget ( "Set All Masks",
				    xmPushButtonWidgetClass,
				    form, 
				    XmNtopAttachment,   XmATTACH_WIDGET,
				    XmNtopWidget,       reset,
				    XmNleftAttachment,  XmATTACH_FORM,
				    XmNrightAttachment, XmATTACH_FORM,
				    NULL );

    XtAddCallback ( set, XmNactivateCallback, 
		    (XtCallbackProc)set_masksCB, NULL );

    disMiss = create_dismiss_button ( form, shell );

    XtVaSetValues ( disMiss,
		    XmNtopAttachment,    XmATTACH_WIDGET,
		    XmNtopWidget,        set,
		    XmNleftAttachment,   XmATTACH_FORM,
		    XmNrightAttachment,  XmATTACH_FORM,
		    XmNbottomAttachment, XmATTACH_FORM,
		    NULL );


    mask_pack.shell = shell;
    mask_pack.maskScreen = maskScreen;

    DEBUG_TRACE_OUT printf( "Leaving CreatemaskWindow\n" );

    return (shell);
}



/*
 * create_contour_legend - a procedure that creates a small popup
 * widget displaying the contour levels and their associated colors.  This
 * widget also contains two buttons that can be used to display the widgets
 * used to change the contour levels and colors. 
 *
 * Note:  Supplied parent MUST be a form widget class.
 *
 * David Helzer 7/16/97
 */
 
Widget create_contour_legend (Widget parent) 
{
   Widget    contour_legend_form, contour_legend_scroll;
   Widget    change_level_values_button, change_level_colors_button;

   DEBUG_TRACE_IN printf( "Entering create_contour_legend\n");

   contour_legend_form = XtVaCreateManagedWidget ("contour_legend_form",
                                                  xmFormWidgetClass,
                                                  parent,
                                                  XmNtopAttachment, XmATTACH_FORM,
                                                  XmNbottomAttachment, XmATTACH_FORM,
                                                  XmNleftAttachment, XmATTACH_FORM,
                                                  XmNrightAttachment, XmATTACH_FORM,
                                                  XmNresizable, FALSE,
                                                  NULL);     
                                                         
   /* 
    * Create a label widget to be displayed at the top of the form. 
    */
    
   contour_legend_label = XtVaCreateManagedWidget ("contour_legend_label", 
                                                  xmLabelWidgetClass, contour_legend_form,
                                                  XmNtopAttachment, XmATTACH_FORM,
                                                  XmNleftAttachment, XmATTACH_FORM,
                                                  XmNrightAttachment, XmATTACH_FORM,
                                                  NULL);
                                                  
                                                  
   /*
    * Create two buttons at the bottom of the widget that will be used
    * to change the contour level values and colors.
    */
    
   change_level_colors_button = XtVaCreateManagedWidget
                                ("change_level_colors_button",
                                 xmPushButtonWidgetClass,
                                 contour_legend_form,
                                 XmNlabelString,
                                 XmStringCreateLocalized ("Change Contour Level Colors"),
                                 XmNleftAttachment, XmATTACH_FORM,
                                 XmNrightAttachment, XmATTACH_FORM,
                                 XmNbottomAttachment, XmATTACH_FORM,
                                 NULL);
                                 
   /* this callback is prototyped in global.h and defined in callbacks.c */
   XtAddCallback (change_level_colors_button, XmNactivateCallback,
                  (XtCallbackProc)ContourColorsPopupCallback, NULL);
  
    
   change_level_values_button = XtVaCreateManagedWidget
                                  ("change_level_values_button",
                                   xmPushButtonWidgetClass,
                                   contour_legend_form,
                                   XmNlabelString, 
                                   XmStringCreateLocalized ("Change Contour Level Values"),
                                   XmNleftAttachment, XmATTACH_FORM,
                                   XmNrightAttachment, XmATTACH_FORM,  
                                   XmNbottomAttachment, XmATTACH_WIDGET,
                                   XmNbottomWidget, change_level_colors_button,    
                                   NULL);   
                                                                      
    /* this callback is prototyped in global.h and defined in callbacks.c */
    XtAddCallback (change_level_values_button, XmNactivateCallback,
                   (XtCallbackProc)contour_levels_callback, NULL);


   /*
    * Create a form widget in a scrolled window to display the contour level values.
    * This will eventually hold whatever widget it is that is to display the
    * levels and the colors.
    */

   contour_legend_scroll = XtVaCreateManagedWidget ("contour_legend_scroll",
                                                    xmScrolledWindowWidgetClass, 
                                                    contour_legend_form,
                                                    XmNtopAttachment, XmATTACH_WIDGET,
                                                    XmNtopWidget, contour_legend_label,
                                                    XmNbottomAttachment, XmATTACH_WIDGET,
                                                    XmNbottomWidget, change_level_values_button,
                                                    XmNleftAttachment, XmATTACH_FORM,
                                                    XmNrightAttachment, XmATTACH_FORM,
                                                    XmNscrollingPolicy, XmAUTOMATIC,
                                                    XmNresizable, FALSE,
                                                    NULL);


   contour_legend = XtVaCreateManagedWidget ("contour_legend",
                                             xmFormWidgetClass, contour_legend_scroll,
                                             NULL); 

   DEBUG_TRACE_OUT printf( "Leaving create_contour_legend\n");

   return contour_legend_form;
}



/*
 * CreatedrawingAreaShell() - a procedure that generates the large window
 * to display the 512x512 image and various control buttons.  When the 
 * "Reveal Legends" button is pressed, the window enlarges to reveal the
 * legend showing the contour levels and their colors to be displayed.  
 */
 
Widget CreatedrawingAreaShell ( Widget parent ) 
{
    Arg    	args[512];
    Cardinal   	argcnt = 0;
    Boolean     argok;
    Widget shell, shellWindow, drawingAreaFrame;
    Widget printButtonFrame, printButton;
    static char yellowstring[] = "yellow";
    XmString label_xmstring;
    Widget reveal_legend_frame, reveal_info_frame;
    Widget legend, drawing_area_form;
    Widget locaterButtonFrame, locaterButtonForm, locaterFrame;
    Widget scrolled_window, inner_info_form;
    
    DEBUG_TRACE_IN printf( "Entering CreatedrawingAreaShell\n" );

    argcnt = 0;
    XtSetArg( args[argcnt], XmNallowShellResize, True ); argcnt++;
    XtSetArg( args[argcnt], XmNx, 15 ); argcnt++;
    XtSetArg( args[argcnt], XmNy, 25 ); argcnt++;
    shell = XtCreatePopupShell("seraDose:  Image Contouring",
                               xmDialogShellWidgetClass,
                               parent,
                               args,
                               argcnt);


    argcnt = 0;
    XtSetArg(args[argcnt], XmNshadowType, XmSHADOW_IN); argcnt++;
    XtSetArg(args[argcnt], XmNshadowThickness, 5); argcnt++;
    shellWindow = XmCreateFrame(shell, "shellWindow", args, argcnt);


    shellWindowForm = XtVaCreateManagedWidget("shellWindowForm",
                                              xmFormWidgetClass, shellWindow,
                                              NULL);

    drawing_area_form = XtVaCreateManagedWidget ("drawing_area_form", 
                                                 xmFormWidgetClass, shellWindowForm,
                                                 NULL);

    contour_info_widget = XtVaCreateWidget ( "info_area_form", xmFormWidgetClass,
                                             shellWindowForm,
                                             XmNheight, 200,
                                             XmNtopAttachment, XmATTACH_WIDGET,
                                             XmNtopWidget, drawing_area_form,
                                             XmNtopOffset, 3,
                                             XmNrightAttachment, XmATTACH_FORM,
                                             XmNrightOffset, 3, 
                                             XmNleftAttachment, XmATTACH_FORM,
                                             XmNleftOffset, 3,
                                             XmNbottomAttachment, XmATTACH_FORM,
                                             XmNbottomOffset, 3,
                                             NULL );    

    XtSetArg ( args[0], XmNeditMode, XmMULTI_LINE_EDIT );
    XtSetArg ( args[1], XmNscrollHorizontal, False );
    XtSetArg ( args[2], XmNwordWrap, True );
    XtSetArg ( args[3], XmNtopAttachment, XmATTACH_FORM );
    XtSetArg ( args[4], XmNrightAttachment, XmATTACH_FORM );
    XtSetArg ( args[5], XmNleftAttachment, XmATTACH_FORM );
    XtSetArg ( args[6], XmNbottomAttachment, XmATTACH_FORM );
    contour_info_text = XmCreateScrolledText ( contour_info_widget, "contour_info_text", args, 7 );
    XtManageChild ( contour_info_text );
    
    drawingAreaFrame = XtVaCreateManagedWidget("drawingAreaFrame",
                                               xmFrameWidgetClass, drawing_area_form,
                                               XmNtopAttachment, XmATTACH_FORM,
                                               XmNleftAttachment, XmATTACH_FORM,
                                               XmNrightAttachment, XmATTACH_FORM,
                                               XmNshadowType, XmSHADOW_OUT,
                                               XmNshadowThickness, 2,
                                               NULL);
    
    mainWindowDrawingArea = XtVaCreateManagedWidget("mainWindowDrawingArea",
                                                    xmDrawingAreaWidgetClass, drawingAreaFrame,
                                                    XmNwidth, 512,
                                                    XmNheight, 512,
                                                    XmNresizable, False,
                                                    NULL);
						  
    XtAddEventHandler ( mainWindowDrawingArea, ExposureMask, FALSE, 
			(XtEventHandler)load_imageEH, NULL );


    contourTextLabel = XtVaCreateManagedWidget("contourLabelForm",
                                               xmLabelWidgetClass, drawing_area_form,
                                               XmNtopAttachment, XmATTACH_WIDGET,
                                               XmNtopWidget, drawingAreaFrame,
                                               XmNleftAttachment, XmATTACH_FORM,
                                               XmNrightAttachment, XmATTACH_FORM,
                                               XmNheight, 40,
                                               NULL);
					     
					     
    labelContours("");   /* no contours yet --> send empty string */


    /* setup some event handlers for pointer motion in the drawing area */
    XtAddEventHandler(mainWindowDrawingArea, ButtonReleaseMask, FALSE,
                      (XtEventHandler)unclickCB, (XtPointer)1);
    XtAddEventHandler(mainWindowDrawingArea, ButtonPressMask, FALSE,  
                      (XtEventHandler)clickCB, (XtPointer)1);
    XtAddEventHandler(mainWindowDrawingArea, PointerMotionMask, FALSE,
                      (XtEventHandler) update_locater, (XtPointer) NULL);
					 
    /*
     * Create a "Reveal Legend" button to click to display the legend 
     * showing the current contour level values and their associated colors
     *  David Helzer 7-97
     */
 					 
    reveal_legend_frame = XtVaCreateManagedWidget ("reveal_legend_frame", 
                                                   xmFrameWidgetClass, drawing_area_form,
                                                   XmNtopAttachment, XmATTACH_WIDGET,
                                                   XmNtopWidget, contourTextLabel,
                                                   XmNrightAttachment, XmATTACH_FORM,
                                                   XmNbottomAttachment, XmATTACH_FORM,
                                                   XmNshadowType, XmSHADOW_OUT,
                                                   NULL);
                                                 
    label_xmstring = XmStringCreateLtoR ("Legend", 
                                         XmFONTLIST_DEFAULT_TAG);
                                                 
    reveal_legend_button = XtVaCreateManagedWidget ("reveal_legend_button",
                                                    xmToggleButtonWidgetClass, 
                                                    reveal_legend_frame,
                                                    XmNlabelType, XmSTRING,
                                                    XmNlabelString, label_xmstring,
                                                    NULL);
                                                                                                   
    XmStringFree (label_xmstring);
  
    /* 
     * Add a callback for the "Reveal Legend" button.  This callback 
     * will manage/unmanage the legend depending on the button's 
     * current status.
     */
   
    XtAddCallback (reveal_legend_button, XmNvalueChangedCallback,
                   reveal_legend_callback, NULL);

    reveal_info_frame = XtVaCreateManagedWidget ("reveal_info_frame", 
                                                 xmFrameWidgetClass, drawing_area_form,
                                                 XmNtopAttachment, XmATTACH_WIDGET,
                                                 XmNtopWidget, contourTextLabel,
                                                 XmNrightAttachment, XmATTACH_WIDGET,
                                                 XmNrightWidget, reveal_legend_frame,
                                                 XmNbottomAttachment, XmATTACH_FORM,
                                                 XmNshadowType, XmSHADOW_OUT,
                                                 NULL);
    
    label_xmstring = XmStringCreateLtoR ( "Info", 
                                          XmFONTLIST_DEFAULT_TAG );
                                                 
    reveal_info_button = XtVaCreateManagedWidget ( "reveal_info_button",
                                                   xmToggleButtonWidgetClass, 
                                                   reveal_info_frame,
                                                   XmNlabelType, XmSTRING,
                                                   XmNlabelString, label_xmstring,
                                                   NULL);
                                                                                                   
    XmStringFree ( label_xmstring );
  
    /* 
     * Add a callback for the "Reveal Legend" button.  This callback 
     * will manage/unmanage the legend depending on the button's 
     * current status.
     */
   
    XtAddCallback (reveal_info_button, XmNvalueChangedCallback,
                   reveal_info_callback, NULL);

    /*
     * Create a print button to print the current 512x512 image
     */	
  				 
    printButtonFrame = XtVaCreateManagedWidget ("printButtonFrame",
                                                xmFrameWidgetClass, drawing_area_form,
                                                XmNtopAttachment, XmATTACH_WIDGET,
                                                XmNtopWidget, contourTextLabel,
                                                XmNrightAttachment, XmATTACH_WIDGET,
                                                XmNrightWidget, reveal_info_frame,
                                                XmNbottomAttachment, XmATTACH_FORM,
                                                XmNshadowType, XmSHADOW_OUT,
                                                NULL);

    printButton = XtVaCreateManagedWidget ("  Print  ", 
                                           xmPushButtonWidgetClass, printButtonFrame,
                                           NULL);

    XtAddCallback (printButton, XmNactivateCallback, 
                   (XtCallbackProc)PrintImageCallback, (XtPointer) 2);


    /*
     * Create a "Locate" button and text next to it to display the current cursor position.
     */

    locaterFrame = XtVaCreateManagedWidget ("locaterFrame",
                                            xmFrameWidgetClass, drawing_area_form,
                                            XmNtopAttachment, XmATTACH_WIDGET,
                                            XmNtopWidget, contourTextLabel,
                                            XmNleftAttachment, XmATTACH_FORM,
                                            XmNbottomAttachment, XmATTACH_FORM,
                                            XmNrightAttachment, XmATTACH_WIDGET,
                                            XmNrightWidget, printButtonFrame,
                                            XmNshadowType, XmSHADOW_OUT,
                                            NULL);

    locaterButtonForm = XtVaCreateManagedWidget ("locaterButtonForm", 
                                                 xmFormWidgetClass, locaterFrame,
                                                 NULL);

    locaterButtonFrame = XtVaCreateManagedWidget ("locaterButtonFrame",
                                                  xmFrameWidgetClass, locaterButtonForm,
                                                  XmNshadowType, XmSHADOW_OUT,
                                                  NULL);
  
    label_xmstring = XmStringCreateLtoR ("Locate",
                                         XmFONTLIST_DEFAULT_TAG);

    locaterButton = XtVaCreateManagedWidget("locaterButton",  
                                            xmToggleButtonGadgetClass, locaterButtonFrame,
                                            XmNselectColor, 
                                            CONVERT(shell, yellowstring, "Pixel", 0, &argok),
                                            XmNfillOnSelect, TRUE,
                                            XmNlabelString, label_xmstring,
                                            NULL);

    XmStringFree (label_xmstring);
					  
    XtAddCallback (locaterButton, XmNarmCallback, 
		   (XtCallbackProc)ReportToggleArmCB, NULL);
				 

    /* 
     * Create a label widget next to the locater button widget to display the
     * current position of the cursor when "locate" is selected
     */
    label_xmstring = XmStringCreateLtoR ("                      ",
                                         XmFONTLIST_DEFAULT_TAG);

    locaterLabel = XtVaCreateManagedWidget("Locater",
                                           xmLabelWidgetClass, locaterButtonForm,
                                           XmNtopAttachment, XmATTACH_FORM,
                                           XmNtopOffset, 5,
                                           XmNleftAttachment, XmATTACH_WIDGET,
                                           XmNleftWidget, locaterButtonFrame,
                                           XmNrightAttachment, XmATTACH_NONE,
                                           XmNbottomAttachment, XmATTACH_NONE,
                                           XmNbottomOffset, 5,
                                           XmNlabelString, label_xmstring,
                                           NULL);

    XmStringFree (label_xmstring);



    /* 
     * create the legend showing the contour levels to be displayed and their
     * associated colors to the right of the 512x512 image
     */

    contour_legend_widget = XtVaCreateWidget ("contour_legend_widget",
                                              xmFormWidgetClass, shellWindowForm,
                                              XmNleftAttachment, XmATTACH_WIDGET,
                                              XmNleftWidget, drawing_area_form,
                                              XmNtopAttachment, XmATTACH_FORM,
                                              XmNrightAttachment, XmATTACH_FORM,
                                              XmNheight, 512,
                                              XmNwidth, 200,
                                              NULL);

    legend = create_contour_legend (contour_legend_widget);  
    /*
      XtVaSetValues (legend,
      XmNleftAttachment, XmATTACH_FORM,
      XmNrightAttachment, XmATTACH_FORM,
      XmNtopAttachment, XmATTACH_FORM,
      NULL);*/
 
    DEBUG_TRACE_OUT printf( "Leaving CreatedrawingAreaShell\n" );

    return (shellWindow);
}



/***************************************************************************/
/* Create confirm dialog */
/* mwf taken from bnct on 1-13-97 */
void create_confirm_popup(void)
{
   Arg al[10];
   int ac;
   XmString yes,no;
   
   DEBUG_TRACE_IN printf( "Entering create_confirm_popup\n" );

   yes = XmStringCreateSimple("Accept");
   no  = XmStringCreateSimple("TryAgain");

   /* create (but DO NOT manage) the confirm dialog */
   ac=0;
   XtSetArg(al[ac], XmNtitle, "Confirmation dialog"); ac++;
   XtSetArg(al[ac], XmNdialogStyle, XmDIALOG_PRIMARY_APPLICATION_MODAL); ac++;
   Confirm_dialog=XmCreateMessageDialog(image_matrix.shell,"Confirm_dialog",al,ac);
   XtVaSetValues(Confirm_dialog,
                 XmNokLabelString,yes,
                 XmNcancelLabelString,no, NULL);
   XtAddCallback(Confirm_dialog,XmNokCallback, (XtCallbackProc)Confirm_dialog_CB, NULL );
   XtAddCallback(Confirm_dialog,XmNcancelCallback, (XtCallbackProc)Confirm_dialog_CB, NULL);
   XtUnmanageChild(XmMessageBoxGetChild(Confirm_dialog,XmDIALOG_HELP_BUTTON));

   DEBUG_TRACE_OUT printf( "Leaving create_confirm_popup\n" );
}


/******************************************************************************/
/*  Function Name:  error_popup                                               */
/*                                                                            */
/*  Input:  String to display in popup dialog                                 */
/*                                                                            */
/*  Output:  None                                                             */
/*                                                                            */
/*  Return:  None                                                             */
/*                                                                            */
/*  Description:                                                              */
/*   This function displays the text passed as a parameter in an error dialog */
/*    widget and processes other events until a response is made.  Then the   */
/*    dialog is unmanaged.                                                    */
/*    									      */
/******************************************************************************/

void ErrorPopupOkCB (Widget w, Widget popup, XmAnyCallbackStruct *cbs);

void error_popup (char *message)
{
   static Widget error_popup = NULL;
   Arg al[20];
   int ac;
   XmString xstring;

   DEBUG_TRACE_IN printf( "Entering error_popup\n" );
  
   /* Sound the bell */
   XBell (XtDisplay (MainWindow), 100);

   if (error_popup == NULL)
   {
      /* create the error dialog widget */
      ac=0;
      XtSetArg(al[ac], XmNdialogStyle, XmDIALOG_PRIMARY_APPLICATION_MODAL); ac++;
      error_popup=XmCreateErrorDialog(MainWindow,"error",al,ac);
      XtAddCallback(error_popup, XmNokCallback, 
                 (XtCallbackProc)ErrorPopupOkCB, error_popup);
      XtUnmanageChild(XmMessageBoxGetChild(error_popup,XmDIALOG_CANCEL_BUTTON));
      XtUnmanageChild(XmMessageBoxGetChild(error_popup,XmDIALOG_HELP_BUTTON));
   } 

   /*
    * Build the message string and then manage the widget.
    */
   xstring = XmStringCreateLtoR (message, XmSTRING_DEFAULT_CHARSET);
   XtVaSetValues 
   (  error_popup, 
      XmNmessageString, xstring, 
      XmNx, 100, 
      XmNy, 100, 
      NULL
   );
   XmStringFree (xstring);

   set_cursor(CURSOR_ERROR);

   XtManageChild (error_popup);

   DEBUG_TRACE_OUT printf( "Leaving error_popup\n" );
} /* end of error_popup */


void ErrorPopupOkCB (Widget w, Widget popup, XmAnyCallbackStruct *cbs)
{
   DEBUG_TRACE_IN printf( "Entering ErrorPopupOkCB\n" );
   set_cursor(CURSOR_DEFAULT);

   XtUnmanageChild(popup);

   DEBUG_TRACE_OUT printf( "Leaving ErrorPopupOkCB\n" );
   return;
}
